### ISSUE TITLE
ECONNRESET error

### ISSUE THREAD

**Issue by jeangui** [lukehorvat/graphql-trello#2]
Hello,

I am trying to use your library.
I am getting a "ECONNRESET error".

`{ Error: read ECONNRESET
    at exports._errnoException (util.js:1020:11)
    at TLSWrap.onread (net.js:568:26)
  message: 'read ECONNRESET',
  locations: [ { line: 12, column: 11 } ],
  path: [ 'getBoard', 'lists', 6, 'cards', 21, 'comments' ] }
`

Have you any idea of what could cause this problem ?

Best regards

Jeangui

**Comment by lukehorvat** [comment]
I'm not entirely sure, but I think it may have been a Trello API change. I updated the `node-trello` package version and the error seems to have gone away.

Try the latest release (v0.0.3) and let me know if it works for you.

**Comment by jeangui** [comment]
hello Luke,

Thanks a lot for your help.
I have just tested with the good version 0.0.3 et with the get-board.js sample.
I am getting the following error

`TRELLO_KEY=XXXXXXX TRELLO_TOKEN=YYYYYY TRELLO_BOARD_ID=ZZZZ ./node_modules/babel-cli/bin/babel-node.js --presets node6 ./examples/get-board.js
{ Error: Cannot return null for non-nullable field Label.color.
    at completeValue (C:\Users\jelalann\Documents\4 - SANDBOX\TRELLO\GRAPHQL-TRELLO\graphql-trello\node_modules\graphql\execution\execute.js:569:13)
    at completeValueWithLocatedError (C:\Users\jelalann\Documents\4 - SANDBOX\TRELLO\GRAPHQL-TRELLO\graphql-trello\node_modules\graphql\execution\execute.js:518:21)
    at completeValueCatchingError (C:\Users\jelalann\Documents\4 - SANDBOX\TRELLO\GRAPHQL-TRELLO\graphql-trello\node_modules\graphql\execution\execute.js:488:12)
    at resolveField (C:\Users\jelalann\Documents\4 - SANDBOX\TRELLO\GRAPHQL-TRELLO\graphql-trello\node_modules\graphql\execution\execute.js:462:10)
    at C:\Users\jelalann\Documents\4 - SANDBOX\TRELLO\GRAPHQL-TRELLO\graphql-trello\node_modules\graphql\execution\execute.js:274:18
    at Array.reduce (native)
    at executeFields (C:\Users\jelalann\Documents\4 - SANDBOX\TRELLO\GRAPHQL-TRELLO\graphql-trello\node_modules\graphql\execution\execute.js:271:42)
    at collectAndExecuteSubfields (C:\Users\jelalann\Documents\4 - SANDBOX\TRELLO\GRAPHQL-TRELLO\graphql-trello\node_modules\graphql\execution\execute.js:719:10)
    at completeObjectValue (C:\Users\jelalann\Documents\4 - SANDBOX\TRELLO\GRAPHQL-TRELLO\graphql-trello\node_modules\graphql\execution\execute.js:701:10)
    at completeValue (C:\Users\jelalann\Documents\4 - SANDBOX\TRELLO\GRAPHQL-TRELLO\graphql-trello\node_modules\graphql\execution\execute.js:598:12)
    at completeValueWithLocatedError (C:\Users\jelalann\Documents\4 - SANDBOX\TRELLO\GRAPHQL-TRELLO\graphql-trello\node_modules\graphql\execution\execute.js:518:21)
    at completeValueCatchingError (C:\Users\jelalann\Documents\4 - SANDBOX\TRELLO\GRAPHQL-TRELLO\graphql-trello\node_modules\graphql\execution\execute.js:494:21)
    at C:\Users\jelalann\Documents\4 - SANDBOX\TRELLO\GRAPHQL-TRELLO\graphql-trello\node_modules\graphql\execution\execute.js:621:25
    at Array.forEach (native)
    at forEach (C:\Users\jelalann\Documents\4 - SANDBOX\TRELLO\GRAPHQL-TRELLO\graphql-trello\node_modules\iterall\index.js:272:25)
    at completeListValue (C:\Users\jelalann\Documents\4 - SANDBOX\TRELLO\GRAPHQL-TRELLO\graphql-trello\node_modules\graphql\execution\execute.js:617:24)
  message: 'Cannot return null for non-nullable field Label.color.',
  locations: [ { line: 17, column: 13 } ],
  path: [ 'getBoard', 'lists', 0, 'cards', 3, 'labels', 3, 'color' ] }`

What could be the problem ?

Thanks 

Best

jeangui

**Comment by jeangui** [comment]
sorry. it may be a problem with trello api. When I change my graphql query it does work ! 👍 

thanks a lot

**Comment by lukehorvat** [comment]
No problem. 🙂
